export const userConstants = {
    ADD_USERS: 'ADD_USERS',
    DELETE_USER: 'DELETE_USER',
    DELETE_ALL_USERS : 'DELETE_ALL_USERS',
    SHOW_PASSWORD : 'SHOW_PASSWORD',
    SUBMIT : 'SUBMIT',
    USER_DETAIL : 'USER_DETAIL',
    ADD_CURRENT_USER: 'ADD_CURRENT_USER',
    SHOW_DB: 'SHOW_DB'
}